# application-prod.properties
spring.application.name=CakesManagement-Prod

# חיבור לבסיס נתונים מאובטח בפרודקשן (הפרטים ייקראו ממשתני סביבה מאובטחים)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver

# כיבוי מוחלט של קונסולת ה-H2 למניעת פריצות
spring.h2.console.enabled=false

# בפרודקשן לא משתמשים ב-update אלא רק מוודאים (validate) שהבסיס נתונים תואם לאפליקציה
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# הגדרת מקורות מורשים (CORS) בצורה דינמית לפרודקשן
app.cors.allowed-origins=${ALLOWED_ORIGINS}

# מפתח JWT לפרודקשן
jwt.secret=${JWT_SECRET}

# שרת מיילים לפרודקשן
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true