spring.application.name=CakesMenagement


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# הגדרת הפרופיל הפעיל כברירת מחדל
spring.profiles.active=dev

# מפתח ה-JWT לפיתוח מקומי בלבד
jwt.secret=

# הגדרות פיתוח - בסיס נתונים מקומי H2
spring.datasource.url=jdbc:h2:./data/cakesDB;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
app.cors.allowed-origins=http://localhost:8081

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=b1e740001@smtp-brevo.com
spring.mail.password=
app.frontend-url=https://localhost:8081
cloudinary.cloud-name=lnp5ex6r
cloudinary.api-key=
cloudinary.api-secret=
spring.servlet.multipart.max-file-size=8MB
spring.servlet.multipart.max-request-size=8MB
