spring.application.name=CakesMenagement
# ????? ??? ??? ???????
spring.datasource.url=jdbc:h2:./data/cakesDB;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ????? ???????? ?? H2 ????? ????? ???????
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ????? Hibernate (?????????, ?? ??? ????? ?-JPA/Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
app.cors.allowed-origins=http://localhost:8081
jwt.secret=${JWT_SECRET:MySuperSecretKeyForCakesBoutiqueProductionReady12$3$21456789!}
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true